### ISSUE TITLE
what is the proper way to use cocoapods latest version?

### ISSUE THREAD

**Issue by sibelius** [CircleCI-Public/circleci-demo-react-native#13]

**Comment by nan140114** [comment]
cocoapods version depends on xcode version that you choose on the config.yml. Each xcode version is related to a virtual machine with specific software installed. check: https://circleci.com/docs/2.0/testing-ios/?utm_medium=SEM&utm_source=gnb&utm_campaign=SEM-gb-DSA-Eng-ni&utm_content=&utm_term=dynamicSearch-&gclid=CjwKCAjw7e_0BRB7EiwAlH-goBOjCVBO4LBlFhiHhwjvR8sSPUzCjMe_3XhLnU9mkOmJCNLPrXR9ExoCop8QAvD_BwE#supported-xcode-versions

**Comment by sibelius** [comment]
Tks
