### ISSUE TITLE
React Native 0.60 Invalid Podfile

### ISSUE THREAD

**Issue by dawidvdh** [CircleCI-Public/circleci-demo-react-native#14]
Receiving the following issue with react-native 0.60

```
Invalid `Podfile` file: 785: unexpected token at '{
...
 #  from /Users/distiller/app/ios/Podfile:50
 #  -------------------------------------------
 #  
 >    use_native_modules!
 #  end
 #  -------------------------------------------
```
[See on CircleCi Discuss](https://discuss.circleci.com/t/react-native-0-60-use-native-modules/31474)

**Comment by davidfant** [comment]
@dawidvdh did you manage to solve this? I've installed `@react-native-community/cli@2.8.0`, but am still seeing this error on CircleCI.

FYI when I SSH into the CircleCI instance and run `bundle exec pod install` manually, it works fine.

**Comment by dawidvdh** [comment]
@davidfant removing my lock file and my `node_modules` then reinstalling resolved my issue which I assume basically only upgraded the cli

**Comment by davidfant** [comment]
@dawidvdh thanks a lot, this saved me many hours 😍

**Comment by sibelius** [comment]
@dawidvdh you avoid commiting your Podfile.lock?

**Comment by dawidvdh** [comment]
@sibelius no not at all so just removing your `package-lock.json` or `yarn.lock` depending on what you use and then reinstalling will update the ` @react-native-community/cli` to the latest version which solves this issue.

That or you can manually go through your lock file and update all instances of `@react-native-community/cli` to the latest version.

**Comment by A-Tokyo** [comment]
My issue was that I had `react-native-cli` as a dependency, Everything worked fine once I removed it and the error didn't show up again. Hope somebody might find this useful.
